version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  kurento:
    build: ./kurento
    ports:
      - "8888:8888"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - kurento
    command: [ "./wait-for-it.sh", "kurento:8888", "--strict", "--", "java", "--enable-preview", "-jar", "/usr/local/lib/app.jar"]
